/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas_Administrador;

import Conexión.Conexión;
import Entidades.Empresa;
import Entidades.Persona;
import Entidades.Persona2;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JTextField;
import oracle.jdbc.OracleTypes;
import java.awt.Point;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igore
 */
public class RegistroClientes extends javax.swing.JPanel {

    /**
     * Creates new form RegistroClientes
     */
    Funciones_Empresa fe = new Funciones_Empresa();
    Funciones_Persona fp = new Funciones_Persona();

    public RegistroClientes() {

        initComponents();
        fe.listarEmpresas(this);

    }

    public RegistroClientes(JTable jListaEmpresa) {
        this.jListaEmpresa = jListaEmpresa;
    }

    public JTable getjListaEmpresa() {
        return jListaEmpresa;
    }

    public void setjListaEmpresa(JTable jListaEmpresa) {
        this.jListaEmpresa = jListaEmpresa;
    }

    public RegistroClientes(JTextField RutEmpresa) {
        this.RutEmpresa = RutEmpresa;
    }

    public JTextField getDireccionEmpresa() {
        return DireccionEmpresa;
    }

    public void setDireccionEmpresa(JTextField DireccionEmpresa) {
        this.DireccionEmpresa = DireccionEmpresa;
    }

    public JTextField getEmailEmpresa() {
        return EmailEmpresa;
    }

    public void setEmailEmpresa(JTextField EmailEmpresa) {
        this.EmailEmpresa = EmailEmpresa;
    }

    public JButton getGuardarEmpresa() {
        return GuardarEmpresa;
    }

    public void setGuardarEmpresa(JButton GuardarEmpresa) {
        this.GuardarEmpresa = GuardarEmpresa;
    }

    public JTextField getNomEmpresa() {
        return NomEmpresa;
    }

    public void setNomEmpresa(JTextField NomEmpresa) {
        this.NomEmpresa = NomEmpresa;
    }

    public JTextField getRubroEmpresa() {
        return RubroEmpresa;
    }

    public void setRubroEmpresa(JTextField RubroEmpresa) {
        this.RubroEmpresa = RubroEmpresa;
    }

    public JTextField getRutEmpresa() {
        return RutEmpresa;
    }

    public void setRutEmpresa(JTextField RutEmpresa) {
        this.RutEmpresa = RutEmpresa;
    }

    public JTextField getTelEmpresa() {
        return TelEmpresa;
    }

    public void setTelEmpresa(JTextField TelEmpresa) {
        this.TelEmpresa = TelEmpresa;
    }

    public void llenarProfesionales() {

        ArrayList<Persona> listaPersona = fp.getPersona();

        cbxProfesionalesAd.removeAllItems();

        for (int i = 0; i < listaPersona.size(); i++) {
            cbxProfesionalesAd.addItem(new Persona(listaPersona.get(i).getId_persona(),listaPersona.get(i).getNombre()));
        }

    }
    
    public void llenarRepresentantes() {

        ArrayList<Persona2> listaPersona2 = fp.getPersona2();

        cbxRepre.removeAllItems();

        for (int i = 0; i < listaPersona2.size(); i++) {
            cbxRepre.addItem(new Persona2(listaPersona2.get(i).getId_persona(), listaPersona2.get(i).getNombre(), listaPersona2.get(i).getRut()));
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TelefonoEmpresa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomEmpresa = new javax.swing.JTextField();
        RubroEmpresa = new javax.swing.JTextField();
        DireccionEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmailEmpresa = new javax.swing.JTextField();
        TelEmpresa = new javax.swing.JTextField();
        GuardarEmpresa = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        RutEmpresa = new javax.swing.JTextField();
        jModificar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        PassEmpresa = new javax.swing.JTextField();
        jIde = new javax.swing.JTextField();
        cbxProfesionalesAd = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxRepre = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaEmpresa = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Clientes");

        jLabel2.setText("Nombre Empresa");

        jLabel3.setText("Rut Empresa");

        jLabel4.setText("Rubro Empresa");

        jLabel5.setText("Dirección");

        jLabel6.setText("Email");

        jLabel7.setText("Telefono");

        GuardarEmpresa.setText("Guardar");
        GuardarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEmpresaActionPerformed(evt);
            }
        });

        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jModificar.setText("Modificar");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Contraseña");

        jLabel9.setText("Profesional ");

        jLabel11.setText("Representante");

        javax.swing.GroupLayout TelefonoEmpresaLayout = new javax.swing.GroupLayout(TelefonoEmpresa);
        TelefonoEmpresa.setLayout(TelefonoEmpresaLayout);
        TelefonoEmpresaLayout.setHorizontalGroup(
            TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jIde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(42, 42, 42)
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(RubroEmpresa)
                    .addComponent(DireccionEmpresa)
                    .addComponent(PassEmpresa)
                    .addComponent(cbxRepre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(56, 56, 56)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxProfesionalesAd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(TelEmpresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RutEmpresa))
                        .addGap(58, 58, 58)
                        .addComponent(jLimpiar))
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarEmpresa)
                        .addGap(30, 30, 30)
                        .addComponent(jModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEliminar)))
                .addGap(36, 36, 36))
        );
        TelefonoEmpresaLayout.setVerticalGroup(
            TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jIde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(RutEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DireccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RubroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(EmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLimpiar))))
                .addGap(18, 18, 18)
                .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addComponent(cbxProfesionalesAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuardarEmpresa)
                            .addComponent(jModificar)
                            .addComponent(jEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(PassEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelefonoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11))
                            .addGroup(TelefonoEmpresaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbxRepre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        jPanel1.add(TelefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 990, 290));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 990, 10));

        jListaEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jListaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListaEmpresaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListaEmpresa);

        jButton4.setText("Desactivar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jActualizar.setText("Actualizar");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jActualizar))
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 990, 300));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lista de Clientes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        fe.ModificarEmpresa(this);
        fe.listarEmpresas(this);
    }//GEN-LAST:event_jModificarActionPerformed

    private void GuardarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEmpresaActionPerformed
        int id = cbxProfesionalesAd.getItemAt(cbxProfesionalesAd.getSelectedIndex()).getId_persona();
        fe.validación(this);
        fe.listarEmpresas(this);
    }//GEN-LAST:event_GuardarEmpresaActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        fe.listarEmpresas(this);
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jListaEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaEmpresaMousePressed
        JTable tabla = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = tabla.rowAtPoint(point);
        if (evt.getClickCount() == 1) {
            NomEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 2).toString());
            RutEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 1).toString());
            RubroEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 3).toString());
            EmailEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 5).toString());
            DireccionEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 6).toString());
            TelEmpresa.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 4).toString());
            jIde.setText(jListaEmpresa.getValueAt(jListaEmpresa.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jListaEmpresaMousePressed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        fe.EliminarEmpresa(this);
        fe.listarEmpresas(this);
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        fe.Limpiar(this);
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fe.DesactivarEmpresa(this);
        fe.listarEmpresas(this);
    }//GEN-LAST:event_jButton4ActionPerformed


   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField DireccionEmpresa;
    public javax.swing.JTextField EmailEmpresa;
    private javax.swing.JButton GuardarEmpresa;
    public javax.swing.JTextField NomEmpresa;
    public javax.swing.JTextField PassEmpresa;
    public javax.swing.JTextField RubroEmpresa;
    public javax.swing.JTextField RutEmpresa;
    public javax.swing.JTextField TelEmpresa;
    private javax.swing.JPanel TelefonoEmpresa;
    public javax.swing.JComboBox<Persona> cbxProfesionalesAd;
    public javax.swing.JComboBox<Persona2> cbxRepre;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jEliminar;
    public javax.swing.JTextField jIde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpiar;
    public javax.swing.JTable jListaEmpresa;
    private javax.swing.JButton jModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
