/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/admin.png")).getImage());
        jMayus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jUsuario = new javax.swing.JLabel();
        jContraseña = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLogoLogin = new javax.swing.JLabel();
        jPassContraseña = new javax.swing.JPasswordField();
        LoginBtnSalir = new javax.swing.JPanel();
        jBtnSalir = new javax.swing.JLabel();
        LoginBtnAceptar = new javax.swing.JPanel();
        jBtnAceptar = new javax.swing.JLabel();
        jMayus = new javax.swing.JLabel();
        jHeaderLogin = new javax.swing.JPanel();
        jSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(159, 197, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No Más Accidentes");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asesorias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 480, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsuario.setText("Usuario:");
        jPanel3.add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jContraseña.setText("Contraseña:");
        jPanel3.add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jTextUsuario.setBackground(new java.awt.Color(214, 217, 223));
        jTextUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextUsuario.setBorder(null);
        jTextUsuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextUsuarioComponentAdded(evt);
            }
        });
        jTextUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextUsuarioMousePressed(evt);
            }
        });
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        jTextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextUsuarioKeyTyped(evt);
            }
        });
        jPanel3.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 200, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, 10));

        jLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        jPanel3.add(jLogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPassContraseña.setBackground(new java.awt.Color(214, 217, 223));
        jPassContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jPassContraseña.setBorder(null);
        jPassContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPassContraseñaMousePressed(evt);
            }
        });
        jPassContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassContraseñaActionPerformed(evt);
            }
        });
        jPassContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassContraseñaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassContraseñaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassContraseñaKeyTyped(evt);
            }
        });
        jPanel3.add(jPassContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, -1));

        LoginBtnSalir.setBackground(new java.awt.Color(255, 51, 51));
        LoginBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginBtnSalirMousePressed(evt);
            }
        });

        jBtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setText("Salir");
        jBtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout LoginBtnSalirLayout = new javax.swing.GroupLayout(LoginBtnSalir);
        LoginBtnSalir.setLayout(LoginBtnSalirLayout);
        LoginBtnSalirLayout.setHorizontalGroup(
            LoginBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBtnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginBtnSalirLayout.setVerticalGroup(
            LoginBtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBtnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(LoginBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 90, 30));

        LoginBtnAceptar.setBackground(new java.awt.Color(153, 255, 153));
        LoginBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnAceptarMouseExited(evt);
            }
        });

        jBtnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAceptarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout LoginBtnAceptarLayout = new javax.swing.GroupLayout(LoginBtnAceptar);
        LoginBtnAceptar.setLayout(LoginBtnAceptarLayout);
        LoginBtnAceptarLayout.setHorizontalGroup(
            LoginBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(LoginBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginBtnAceptarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LoginBtnAceptarLayout.setVerticalGroup(
            LoginBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(LoginBtnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginBtnAceptarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(LoginBtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, 30));

        jMayus.setText("mayus activo");
        jMayus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMayusKeyReleased(evt);
            }
        });
        jPanel3.add(jMayus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 480, 470));

        jHeaderLogin.setBackground(new java.awt.Color(159, 197, 248));
        jHeaderLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jHeaderLoginMouseDragged(evt);
            }
        });
        jHeaderLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHeaderLoginMousePressed(evt);
            }
        });

        jSalir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSalir.setText("x");
        jSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jHeaderLoginLayout = new javax.swing.GroupLayout(jHeaderLogin);
        jHeaderLogin.setLayout(jHeaderLoginLayout);
        jHeaderLoginLayout.setHorizontalGroup(
            jHeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderLoginLayout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jHeaderLoginLayout.setVerticalGroup(
            jHeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeaderLoginLayout.createSequentialGroup()
                .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jHeaderLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jBtnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseEntered
        LoginBtnAceptar.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_jBtnAceptarMouseEntered

    private void LoginBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnAceptarMouseExited
        enter();
    }//GEN-LAST:event_LoginBtnAceptarMouseExited

    private void LoginBtnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnSalirMousePressed
        Perfiles p = new Perfiles();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoginBtnSalirMousePressed

    private void LoginBtnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnAceptarMouseEntered
        LoginBtnAceptar.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_LoginBtnAceptarMouseEntered

    private void jBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseExited
        LoginBtnAceptar.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_jBtnAceptarMouseExited

    private void jBtnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMouseEntered
        LoginBtnSalir.setBackground(new Color(255, 0, 51));
    }//GEN-LAST:event_jBtnSalirMouseEntered

    private void jBtnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMouseExited
        LoginBtnSalir.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_jBtnSalirMouseExited

    private void jBtnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMousePressed
        Perfiles p = new Perfiles();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSalirMousePressed

    private void jTextUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUsuarioMousePressed
        jTextUsuario.setForeground(Color.black);
        
    }//GEN-LAST:event_jTextUsuarioMousePressed

    private void jPassContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassContraseñaMousePressed
        jPassContraseña.setForeground(Color.black);
       
    }//GEN-LAST:event_jPassContraseñaMousePressed

    private void jBtnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMousePressed
        enter();
    }//GEN-LAST:event_jBtnAceptarMousePressed

    private void jPassContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassContraseñaActionPerformed

    private void jHeaderLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderLoginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jHeaderLoginMouseDragged

    private void jHeaderLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderLoginMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jHeaderLoginMousePressed

    private void jSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jSalirMouseClicked

    private void jSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalirMouseEntered
        jSalir.setForeground(Color.red);
    }//GEN-LAST:event_jSalirMouseEntered

    private void jSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalirMouseExited
        jSalir.setForeground(Color.black);
    }//GEN-LAST:event_jSalirMouseExited

    private void jMayusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMayusKeyReleased

    }//GEN-LAST:event_jMayusKeyReleased

    private void jPassContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassContraseñaKeyReleased
        
        boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        
        if(capsActivo){
            jMayus.setVisible(true); 
        }else{
            jMayus.setVisible(false); 
        }
              
               
       
    }//GEN-LAST:event_jPassContraseñaKeyReleased

    private void jTextUsuarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextUsuarioComponentAdded
       
    }//GEN-LAST:event_jTextUsuarioComponentAdded

    private void jTextUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioKeyTyped
        jTextUsuario.setForeground(Color.black);
    }//GEN-LAST:event_jTextUsuarioKeyTyped

    private void jPassContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassContraseñaKeyTyped
        jPassContraseña.setForeground(Color.black);
    }//GEN-LAST:event_jPassContraseñaKeyTyped

    private void jTextUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                enter();
            }
    }//GEN-LAST:event_jTextUsuarioKeyPressed

    private void jPassContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassContraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                enter();
            }
    }//GEN-LAST:event_jPassContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public void login() {
        String user = jTextUsuario.getText().trim();
        String pass = String.valueOf(jPassContraseña.getPassword()).trim();

        Profesionales pro1 = new Profesionales();
        Administrador ad = new Administrador();
        CambioContraseña cc = new CambioContraseña();
        try {
            URL url = new URL("http://127.0.0.1:8000/login/" + user + "/" + pass + "?format=json");
            HttpURLConnection curl = (HttpURLConnection) url.openConnection();
            curl.setRequestMethod("GET");
            curl.connect();
            int response = curl.getResponseCode();
            System.out.println("" + response);

            Map<String, String> map = new HashMap<>();
            map.put("200", "correcto");
            map.put("404", "Usuario o Contraseña Incorrecta");
            map.put("500", "Error en el sistema pruebe de nuevo");
            map.put("default", "Error");

            if (response != 200) {
                if (response == 404) {
                    JOptionPane.showMessageDialog(null, map.get("" + response));
                } else if (response == 500) {
                    JOptionPane.showMessageDialog(null, map.get("" + response));
                } else {
                    JOptionPane.showMessageDialog(null, map.get("default"));
                    throw new RuntimeException("Error:" + response);
                }
            } else {

                StringBuilder information = new StringBuilder();
                Scanner s = new Scanner(url.openStream());
                String[] datos = new String[7];
                if (s.hasNext()) {

                    information.append(s.nextLine());

                }
                s.close();
                JSONArray json = new JSONArray(information.toString());

                try {

                    for (int i = 0; i < 1; i++) {
                        JSONObject object = json.getJSONObject(i);
                        datos[0] = String.valueOf(object.getInt("Id_Persona"));
                        datos[1] = object.getString("Nombre");
                        datos[2] = object.getString("Rut");
                        datos[3] = object.getString("A_Paterno");
                        datos[4] = String.valueOf(object.getInt("Id_Rol"));
                        datos[5] = String.valueOf(object.getInt("Id_Estado"));
                    }

                    if (datos[5].equals("1")) {

                        if (datos[4].equals("1")) {

                            ad.setVisible(true);
                            ad.JIDA.setText(datos[0]);
                            ad.JNOMA.setText(datos[1] + " " + datos[3]);
                            ad.JRUTA.setText(datos[2]);
                            cc.jRUT.setText(datos[2]);
                            this.setVisible(false);

                        } else if (datos[4].equals("2")) {

                            pro1.setVisible(true);
                            pro1.JID.setText(datos[0]);
                            pro1.JNOM.setText(datos[1] + " " + datos[3]);
                            pro1.JRUT.setText(datos[2]);
                            cc.jRUT.setText(datos[2]);
                            this.setVisible(false);
                        }
                    } else {
                        getToolkit();
                        System.out.println("error");
                        JOptionPane.showMessageDialog(null, "Usuario Inactivo");
                    }

                } catch (Exception e) {
                    System.out.println("error1");
                }

            }
        } catch (Exception e) {
            System.out.println("error2");
            System.out.println("" + e);
        }
    }
    
    public void enter(){
        if(jTextUsuario.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Ingrese ususario");
        }
        if (jPassContraseña.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese contraseña");

        } else if(jTextUsuario.getText().length() != 0 && jPassContraseña.getText().length() != 0){
            login();
        }

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginBtnAceptar;
    private javax.swing.JPanel LoginBtnSalir;
    private javax.swing.JLabel jBtnAceptar;
    private javax.swing.JLabel jBtnSalir;
    private javax.swing.JLabel jContraseña;
    private javax.swing.JPanel jHeaderLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLogoLogin;
    private javax.swing.JLabel jMayus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassContraseña;
    private javax.swing.JLabel jSalir;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel jUsuario;
    // End of variables declaration//GEN-END:variables
}
