/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexión.CerrarConexion;
import Entidades.Empresa;
import Vistas_Profesional.Asesorías;
import Vistas_Profesional.Capacitación;
import Vistas_Profesional.CheckList;
import Vistas_Profesional.Mejoras;
import Vistas_Profesional.PlanificarVisitas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;


/**
 *
 * @author igore
 */
public class Profesionales extends javax.swing.JFrame {
    
    Empresa empresa = new Empresa();
    CambioContraseña cc = new CambioContraseña();
    int xMouse, yMouse;
    public int id;
    public int id2;
    
    public Profesionales() {

        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/admin.png")).getImage());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuPro = new javax.swing.JPanel();
        jTituloPro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCapacitacion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPlanVisita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckList = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jAsesorias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCerrarSesionPro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMejoras = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jVistasPro = new javax.swing.JPanel();
        jHeaderPro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JID = new javax.swing.JTextField();
        JNOM = new javax.swing.JTextField();
        JRUT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(159, 197, 248));
        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 850));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuPro.setMinimumSize(new java.awt.Dimension(340, 850));
        jMenuPro.setPreferredSize(new java.awt.Dimension(340, 850));
        jMenuPro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTituloPro.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jTituloPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTituloPro.setText("Asesorias");
        jMenuPro.add(jTituloPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 159, 66));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuPro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 122, 159, 13));
        jSeparator1.getAccessibleContext().setAccessibleName("");

        jCapacitacion.setPreferredSize(new java.awt.Dimension(340, 70));
        jCapacitacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear Capacitación");
        jLabel6.setMaximumSize(new java.awt.Dimension(104, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(104, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(104, 16));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jCapacitacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 239, 340, -1));

        jPlanVisita.setPreferredSize(new java.awt.Dimension(340, 70));
        jPlanVisita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planificar Visita");
        jLabel1.setMaximumSize(new java.awt.Dimension(104, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(104, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(104, 16));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPlanVisita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jPlanVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 309, 340, -1));

        jCheckList.setPreferredSize(new java.awt.Dimension(340, 70));
        jCheckList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ChekList");
        jLabel2.setPreferredSize(new java.awt.Dimension(106, 16));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jCheckList.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jCheckList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, 340, -1));

        jAsesorias.setPreferredSize(new java.awt.Dimension(340, 70));
        jAsesorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Asesorías");
        jLabel3.setPreferredSize(new java.awt.Dimension(55, 16));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jAsesorias.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jAsesorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 449, 340, -1));

        jCerrarSesionPro.setMinimumSize(new java.awt.Dimension(340, 70));
        jCerrarSesionPro.setPreferredSize(new java.awt.Dimension(340, 70));
        jCerrarSesionPro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cerrar Sesion");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jCerrarSesionPro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jCerrarSesionPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 340, 70));

        jMejoras.setPreferredSize(new java.awt.Dimension(340, 70));
        jMejoras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Actividades de Mejora");
        jLabel4.setMaximumSize(new java.awt.Dimension(132, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(132, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(132, 16));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jMejoras.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 70));

        jMenuPro.add(jMejoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 340, -1));

        jPanel2.add(jMenuPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        jVistasPro.setBackground(new java.awt.Color(159, 197, 248));
        jVistasPro.setPreferredSize(new java.awt.Dimension(1070, 720));

        javax.swing.GroupLayout jVistasProLayout = new javax.swing.GroupLayout(jVistasPro);
        jVistasPro.setLayout(jVistasProLayout);
        jVistasProLayout.setHorizontalGroup(
            jVistasProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jVistasProLayout.setVerticalGroup(
            jVistasProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel2.add(jVistasPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jHeaderPro.setBackground(new java.awt.Color(159, 197, 248));
        jHeaderPro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jHeaderProMouseDragged(evt);
            }
        });
        jHeaderPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHeaderProMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jHeaderProLayout = new javax.swing.GroupLayout(jHeaderPro);
        jHeaderPro.setLayout(jHeaderProLayout);
        jHeaderProLayout.setHorizontalGroup(
            jHeaderProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jHeaderProLayout.setVerticalGroup(
            jHeaderProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jHeaderPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 40));

        jLabel7.setText("Nombre:");

        jLabel8.setText("Rut:");

        jLabel9.setText("ID:");

        JID.setEditable(false);
        JID.setBackground(new java.awt.Color(214, 217, 223));
        JID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JID.setBorder(null);

        JNOM.setEditable(false);
        JNOM.setBackground(new java.awt.Color(214, 217, 223));
        JNOM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JNOM.setBorder(null);

        JRUT.setEditable(false);
        JRUT.setBackground(new java.awt.Color(214, 217, 223));
        JRUT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JRUT.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Cambiar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel7))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel8))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(497, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JRUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(JNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(JID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 1070, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jPlanVisita.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jPlanVisita.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jCheckList.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jCheckList.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jAsesorias.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jAsesorias.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jMejoras.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jMejoras.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jCerrarSesionPro.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jCerrarSesionPro.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jHeaderProMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderProMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jHeaderProMouseDragged

    private void jHeaderProMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHeaderProMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jHeaderProMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        try {
            CerrarConexion.CerrarSession();
        } catch (SQLException ex) {
            Logger.getLogger(Profesionales.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jCapacitacion.setBackground(new Color(159, 197, 248));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jCapacitacion.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        PlanificarVisitas pv = new PlanificarVisitas();
        pv.setSize(1070, 720);
        pv.setLocation(0, 0);

        jVistasPro.removeAll();
        jVistasPro.add(pv, BorderLayout.CENTER);
        jVistasPro.revalidate();
        jVistasPro.repaint();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        Capacitación ca = new Capacitación();        
        ca.setSize(1070, 720);
        ca.setLocation(0, 0);

        jVistasPro.removeAll();
        jVistasPro.add(ca, BorderLayout.CENTER);
        jVistasPro.revalidate();
        jVistasPro.repaint();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        CheckList ch = new CheckList();
        ch.setSize(1070, 720);
        ch.setLocation(0, 0);

        jVistasPro.removeAll();
        jVistasPro.add(ch, BorderLayout.CENTER);
        jVistasPro.revalidate();
        jVistasPro.repaint();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        Asesorías as = new Asesorías();
        as.setSize(1070, 720);
        as.setLocation(0, 0);

        jVistasPro.removeAll();
        jVistasPro.add(as, BorderLayout.CENTER);
        jVistasPro.revalidate();
        jVistasPro.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        Mejoras mj = new Mejoras();
        mj.setSize(1070, 720);
        mj.setLocation(0, 0);

        jVistasPro.removeAll();
        jVistasPro.add(mj, BorderLayout.CENTER);
        jVistasPro.revalidate();
        jVistasPro.repaint();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesionales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField JID;
    public javax.swing.JTextField JNOM;
    public javax.swing.JTextField JRUT;
    private javax.swing.JPanel jAsesorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jCapacitacion;
    private javax.swing.JPanel jCerrarSesionPro;
    private javax.swing.JPanel jCheckList;
    private javax.swing.JPanel jHeaderPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMejoras;
    private javax.swing.JPanel jMenuPro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPlanVisita;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jTituloPro;
    private javax.swing.JPanel jVistasPro;
    // End of variables declaration//GEN-END:variables
}
